// Code generated by mockery v2.46.3. DO NOT EDIT.

package services

import (
	schemas "smartgas-payment/internal/schemas"

	mock "github.com/stretchr/testify/mock"
)

// MockSwitService is an autogenerated mock type for the SwitService type
type MockSwitService struct {
	mock.Mock
}

// CancelFundReservation provides a mock function with given fields: _a0
func (_m *MockSwitService) CancelFundReservation(_a0 string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CancelFundReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfirmFundReservation provides a mock function with given fields: _a0, _a1
func (_m *MockSwitService) ConfirmFundReservation(_a0 string, _a1 float32) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmFundReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float32) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCustomer provides a mock function with given fields: _a0
func (_m *MockSwitService) CreateCustomer(_a0 *schemas.Customer) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomer")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*schemas.Customer) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*schemas.Customer) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*schemas.Customer) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCard provides a mock function with given fields: _a0, _a1
func (_m *MockSwitService) DeleteCard(_a0 string, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListCardsByCustomer provides a mock function with given fields: _a0
func (_m *MockSwitService) ListCardsByCustomer(_a0 string) ([]schemas.SwitSource, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ListCardsByCustomer")
	}

	var r0 []schemas.SwitSource
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]schemas.SwitSource, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []schemas.SwitSource); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]schemas.SwitSource)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReserveFunds provides a mock function with given fields: _a0
func (_m *MockSwitService) ReserveFunds(_a0 ReserveFundsOpts) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ReserveFunds")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(ReserveFundsOpts) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(ReserveFundsOpts) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(ReserveFundsOpts) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockSwitService creates a new instance of MockSwitService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSwitService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSwitService {
	mock := &MockSwitService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
