// Code generated by mockery v2.46.3. DO NOT EDIT.

package services

import (
	models "smartgas-payment/internal/models"

	mock "github.com/stretchr/testify/mock"

	schemas "smartgas-payment/internal/schemas"
)

// MockSocioSmartService is an autogenerated mock type for the SocioSmartService type
type MockSocioSmartService struct {
	mock.Mock
}

// AccumPoints provides a mock function with given fields: _a0
func (_m *MockSocioSmartService) AccumPoints(_a0 *models.Payment) (*ResponseAccumPoints, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for AccumPoints")
	}

	var r0 *ResponseAccumPoints
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Payment) (*ResponseAccumPoints, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*models.Payment) *ResponseAccumPoints); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ResponseAccumPoints)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.Payment) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGasPumpsByCrePermission provides a mock function with given fields: _a0
func (_m *MockSocioSmartService) GetGasPumpsByCrePermission(_a0 string) ([]schemas.GasPump, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetGasPumpsByCrePermission")
	}

	var r0 []schemas.GasPump
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]schemas.GasPump, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []schemas.GasPump); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]schemas.GasPump)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGasStations provides a mock function with given fields:
func (_m *MockSocioSmartService) GetGasStations() ([]schemas.GasStation, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGasStations")
	}

	var r0 []schemas.GasStation
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]schemas.GasStation, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []schemas.GasStation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]schemas.GasStation)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportTransaction provides a mock function with given fields: opts
func (_m *MockSocioSmartService) ReportTransaction(opts ReportTransactionOpts) error {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for ReportTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(ReportTransactionOpts) error); ok {
		r0 = rf(opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetGasPump provides a mock function with given fields: _a0
func (_m *MockSocioSmartService) SetGasPump(_a0 SetGasPumpOptions) (*schemas.SetGasPump, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetGasPump")
	}

	var r0 *schemas.SetGasPump
	var r1 error
	if rf, ok := ret.Get(0).(func(SetGasPumpOptions) (*schemas.SetGasPump, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(SetGasPumpOptions) *schemas.SetGasPump); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schemas.SetGasPump)
		}
	}

	if rf, ok := ret.Get(1).(func(SetGasPumpOptions) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateEmployee provides a mock function with given fields: opts
func (_m *MockSocioSmartService) ValidateEmployee(opts ValidateEmployeeOpts) (bool, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for ValidateEmployee")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(ValidateEmployeeOpts) (bool, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(ValidateEmployeeOpts) bool); ok {
		r0 = rf(opts)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(ValidateEmployeeOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockSocioSmartService creates a new instance of MockSocioSmartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSocioSmartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSocioSmartService {
	mock := &MockSocioSmartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
