// Code generated by mockery v2.46.3. DO NOT EDIT.

package services

import (
	schemas "smartgas-payment/internal/schemas"

	mock "github.com/stretchr/testify/mock"
)

// MockCustomerService is an autogenerated mock type for the CustomerService type
type MockCustomerService struct {
	mock.Mock
}

// Verify provides a mock function with given fields: _a0
func (_m *MockCustomerService) Verify(_a0 string) (*schemas.Customer, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *schemas.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*schemas.Customer, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *schemas.Customer); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schemas.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockCustomerService creates a new instance of MockCustomerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerService {
	mock := &MockCustomerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
