// Code generated by mockery v2.46.3. DO NOT EDIT.

package services

import (
	schemas "smartgas-payment/internal/schemas"

	mock "github.com/stretchr/testify/mock"

	stripe "github.com/stripe/stripe-go/v72"
)

// MockStripeService is an autogenerated mock type for the StripeService type
type MockStripeService struct {
	mock.Mock
}

// CancelPaymentIntent provides a mock function with given fields: _a0
func (_m *MockStripeService) CancelPaymentIntent(_a0 string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CancelPaymentIntent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCustomer provides a mock function with given fields: _a0
func (_m *MockStripeService) CreateCustomer(_a0 *schemas.Customer) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomer")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*schemas.Customer) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*schemas.Customer) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*schemas.Customer) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePaymentIntent provides a mock function with given fields: _a0, _a1
func (_m *MockStripeService) CreatePaymentIntent(_a0 float64, _a1 string) (*stripe.PaymentIntent, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentIntent")
	}

	var r0 *stripe.PaymentIntent
	var r1 error
	if rf, ok := ret.Get(0).(func(float64, string) (*stripe.PaymentIntent, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(float64, string) *stripe.PaymentIntent); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.PaymentIntent)
		}
	}

	if rf, ok := ret.Get(1).(func(float64, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePaymentMethod provides a mock function with given fields: _a0
func (_m *MockStripeService) DeletePaymentMethod(_a0 string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for DeletePaymentMethod")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListPaymenthMethodsByCustomer provides a mock function with given fields: _a0
func (_m *MockStripeService) ListPaymenthMethodsByCustomer(_a0 string) []*stripe.PaymentMethod {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ListPaymenthMethodsByCustomer")
	}

	var r0 []*stripe.PaymentMethod
	if rf, ok := ret.Get(0).(func(string) []*stripe.PaymentMethod); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*stripe.PaymentMethod)
		}
	}

	return r0
}

// MakeARefund provides a mock function with given fields: _a0, _a1
func (_m *MockStripeService) MakeARefund(_a0 string, _a1 float64) (*stripe.Refund, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for MakeARefund")
	}

	var r0 *stripe.Refund
	var r1 error
	if rf, ok := ret.Get(0).(func(string, float64) (*stripe.Refund, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, float64) *stripe.Refund); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripe.Refund)
		}
	}

	if rf, ok := ret.Get(1).(func(string, float64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockStripeService creates a new instance of MockStripeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStripeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStripeService {
	mock := &MockStripeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
