// Code generated by mockery v2.46.3. DO NOT EDIT.

package services

import mock "github.com/stretchr/testify/mock"

// MockMailService is an autogenerated mock type for the MailService type
type MockMailService struct {
	mock.Mock
}

// SendMail provides a mock function with given fields: _a0
func (_m *MockMailService) SendMail(_a0 SendMailOpts) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendMail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(SendMailOpts) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockMailService creates a new instance of MockMailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailService {
	mock := &MockMailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
