// Code generated by mockery v2.46.3. DO NOT EDIT.

package services

import mock "github.com/stretchr/testify/mock"

// MockDebitService is an autogenerated mock type for the DebitService type
type MockDebitService struct {
	mock.Mock
}

// CancelReservation provides a mock function with given fields: _a0
func (_m *MockDebitService) CancelReservation(_a0 string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CancelReservation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PaymentConfirmation provides a mock function with given fields: _a0, _a1
func (_m *MockDebitService) PaymentConfirmation(_a0 string, _a1 float32) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PaymentConfirmation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float32) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReserveFunds provides a mock function with given fields: _a0
func (_m *MockDebitService) ReserveFunds(_a0 DebitReserveFundsOpts) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ReserveFunds")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(DebitReserveFundsOpts) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(DebitReserveFundsOpts) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(DebitReserveFundsOpts) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockDebitService creates a new instance of MockDebitService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDebitService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDebitService {
	mock := &MockDebitService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
