// Code generated by mockery v2.46.3. DO NOT EDIT.

package services

import mock "github.com/stretchr/testify/mock"

// MockInvoicingService is an autogenerated mock type for the InvoicingService type
type MockInvoicingService struct {
	mock.Mock
}

// GetIeps provides a mock function with given fields: _a0
func (_m *MockInvoicingService) GetIeps(_a0 string) (float64, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetIeps")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (float64, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInvoicePDF provides a mock function with given fields: _a0
func (_m *MockInvoicingService) GetInvoicePDF(_a0 string) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetInvoicePDF")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResendInvoice provides a mock function with given fields: _a0, _a1
func (_m *MockInvoicingService) ResendInvoice(_a0 string, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ResendInvoice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SignInvoice provides a mock function with given fields: _a0
func (_m *MockInvoicingService) SignInvoice(_a0 SignInvoiceOpts) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SignInvoice")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(SignInvoiceOpts) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(SignInvoiceOpts) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(SignInvoiceOpts) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockInvoicingService creates a new instance of MockInvoicingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInvoicingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInvoicingService {
	mock := &MockInvoicingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
