// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injectors

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"gorm.io/gorm"
	"smartgas-payment/api/v1/controllers"
	"smartgas-payment/api/v1/routes"
	"smartgas-payment/config"
	"smartgas-payment/internal/database"
	"smartgas-payment/internal/middlewares"
	"smartgas-payment/internal/repository"
	"smartgas-payment/internal/server/app"
	"smartgas-payment/internal/services"
	"smartgas-payment/internal/tasks"
)

// Injectors from wire.go:

func InitializeServer() (*App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	db, err := database.ConnectDB(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.ProvideUserRepository(db)
	userController := controllers.ProvideUserController(userRepository)
	authMiddleware := middlewares.ProvideAuthMiddleware(userRepository)
	userRoutes := routes.ProvideUserRoutes(userController, authMiddleware)
	authController := controllers.ProvideAuthController(userRepository)
	authRoutes := routes.ProvideAuthRoutes(authController)
	gasStationRepository := repository.ProvideGasStationRepository(db)
	gasPumpRepository := repository.ProvideGasPumpRepository(db)
	socioSmartService := services.ProvideSocioSmartService(configConfig)
	synchronizationRepository := repository.ProvideSynchronizationRepository(db)
	elegibilityRepository := repository.ProvideElegibilityRepository(db)
	customerRepository := repository.ProvideCustomerRepository(db)
	paymentRepository := repository.ProvidePaymentRepository(db)
	synchronizationTask := tasks.ProvideSynchronizationTask(gasStationRepository, gasPumpRepository, socioSmartService, synchronizationRepository, elegibilityRepository, customerRepository, paymentRepository)
	gasStationController := controllers.ProvideGasStationProvider(gasStationRepository, synchronizationTask)
	gasStationRoutes := routes.ProvideGasStationRoutes(gasStationController, authMiddleware)
	campaignRepository := repository.ProvidePromotionRepository(db)
	settingRepository := repository.ProvideSettingRepository(db)
	gasPumpController := controllers.ProvideGasPumpProvider(gasPumpRepository, synchronizationTask, campaignRepository, settingRepository)
	customerService := services.ProvideCustomerService(configConfig)
	stripeService := services.ProvideStripeService()
	switService := services.ProvideSwitService(configConfig)
	customerAuthMiddleware := middlewares.ProvideCustomerAUthMiddleware(customerRepository, customerService, stripeService, switService, elegibilityRepository)
	gasPumpRoutes := routes.ProvideGasPumpRoutes(gasPumpController, authMiddleware, customerAuthMiddleware)
	invoicingService := services.ProvideInvoicingService(configConfig, settingRepository)
	mailService := services.ProvideMailService(configConfig)
	debitService := services.ProvideDebitService(configConfig)
	paymentController := controllers.ProvidePaymentController(paymentRepository, gasPumpRepository, stripeService, configConfig, socioSmartService, switService, invoicingService, mailService, settingRepository, campaignRepository, elegibilityRepository, debitService, customerRepository)
	securityRepository := repository.ProvideSecurityRepository(db)
	securityMiddleware := middlewares.ProvideSecurityMiddleware(securityRepository, gasStationRepository, socioSmartService)
	paymentRoutes := routes.ProvidePaymenRoutes(customerAuthMiddleware, paymentController, authMiddleware, securityMiddleware)
	customerController := controllers.ProvideCustomerController(stripeService, switService, configConfig, settingRepository, customerRepository, elegibilityRepository)
	customerRoutes := routes.ProvideCustomerRoutes(customerAuthMiddleware, customerController, authMiddleware)
	synchronizationController := controllers.ProvideSynchronizationController(synchronizationRepository, synchronizationTask)
	synchronizationRoute := routes.ProvideSynchronizationRoutes(synchronizationController, authMiddleware)
	permissionRepository := repository.ProvidePermissionRepository(db)
	permissionController := controllers.ProvidePermissionController(permissionRepository)
	permissionRoutes := routes.ProvidePermissionRoutes(authMiddleware, permissionController)
	settingController := controllers.ProvideSettingController(settingRepository)
	settingRoutes := routes.ProvideSettingRoutes(authMiddleware, settingController)
	campaignController := controllers.ProvideCampaignController(campaignRepository)
	campaignRoutes := routes.ProvideCampaingRoutes(campaignController, authMiddleware)
	elegibilityController := controllers.ProvideElegibityController(elegibilityRepository)
	elebilityRoutes := routes.ProvideElebilityRoutes(authMiddleware, elegibilityController)
	routesRoutes := routes.ProvideV1Routes(userRoutes, authRoutes, gasStationRoutes, gasPumpRoutes, paymentRoutes, customerRoutes, synchronizationRoute, permissionRoutes, settingRoutes, campaignRoutes, elebilityRoutes)
	engine := app.ProvideGinApp(configConfig, routesRoutes)
	injectorsApp := ProvideApp(engine, db)
	return injectorsApp, nil
}

func InitializeSynchronizationTask() (tasks.SynchronizationTask, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	db, err := database.ConnectDB(configConfig)
	if err != nil {
		return nil, err
	}
	gasStationRepository := repository.ProvideGasStationRepository(db)
	gasPumpRepository := repository.ProvideGasPumpRepository(db)
	socioSmartService := services.ProvideSocioSmartService(configConfig)
	synchronizationRepository := repository.ProvideSynchronizationRepository(db)
	elegibilityRepository := repository.ProvideElegibilityRepository(db)
	customerRepository := repository.ProvideCustomerRepository(db)
	paymentRepository := repository.ProvidePaymentRepository(db)
	synchronizationTask := tasks.ProvideSynchronizationTask(gasStationRepository, gasPumpRepository, socioSmartService, synchronizationRepository, elegibilityRepository, customerRepository, paymentRepository)
	return synchronizationTask, nil
}

func InitializeDB() (*gorm.DB, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	db, err := database.ConnectDB(configConfig)
	if err != nil {
		return nil, err
	}
	return db, nil
}

func InitializeUserRepository() (repository.UserRepository, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	db, err := database.ConnectDB(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.ProvideUserRepository(db)
	return userRepository, nil
}

func InitializeSecurityRepository() (repository.SecurityRepository, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	db, err := database.ConnectDB(configConfig)
	if err != nil {
		return nil, err
	}
	securityRepository := repository.ProvideSecurityRepository(db)
	return securityRepository, nil
}

func InitializeServerWithMocks() (*AppWithMock, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	mockUserRepository := ProvideUserRepositoryMock()
	userController := controllers.ProvideUserController(mockUserRepository)
	authMiddleware := middlewares.ProvideAuthMiddleware(mockUserRepository)
	userRoutes := routes.ProvideUserRoutes(userController, authMiddleware)
	authController := controllers.ProvideAuthController(mockUserRepository)
	authRoutes := routes.ProvideAuthRoutes(authController)
	mockGasStationRepository := ProvideGasStationRepositoryMock()
	mockSynchronizationTask := ProvideSynchronizationTaskMock()
	gasStationController := controllers.ProvideGasStationProvider(mockGasStationRepository, mockSynchronizationTask)
	gasStationRoutes := routes.ProvideGasStationRoutes(gasStationController, authMiddleware)
	mockGasPumpRepository := ProvideGasPumpRepositoryMock()
	mockCampaignRepository := ProvideCampaignRepositoryMock()
	mockSettingRepository := ProvideSettingRepositoryMock()
	gasPumpController := controllers.ProvideGasPumpProvider(mockGasPumpRepository, mockSynchronizationTask, mockCampaignRepository, mockSettingRepository)
	mockCustomerRepository := ProvideCustomerRepositoryMock()
	mockCustomerService := ProvideCustomerServiceMock()
	mockStripeService := ProvideStripeServiceMock()
	mockSwitService := ProvideSwitServiceMock()
	mockElegibilityRepository := ProvideElegibilityRepositoryMock()
	customerAuthMiddleware := middlewares.ProvideCustomerAUthMiddleware(mockCustomerRepository, mockCustomerService, mockStripeService, mockSwitService, mockElegibilityRepository)
	gasPumpRoutes := routes.ProvideGasPumpRoutes(gasPumpController, authMiddleware, customerAuthMiddleware)
	mockPaymentRepository := ProvidePaymentRepositoryMock()
	mockSocioSmartService := ProvideSocioSmartServiceMock()
	mockInvoicingService := ProvideInvoicingServiceMock()
	mockMailService := ProvideMailServiceMock()
	mockDebitService := ProvideDebitServiceMock()
	paymentController := controllers.ProvidePaymentController(mockPaymentRepository, mockGasPumpRepository, mockStripeService, configConfig, mockSocioSmartService, mockSwitService, mockInvoicingService, mockMailService, mockSettingRepository, mockCampaignRepository, mockElegibilityRepository, mockDebitService, mockCustomerRepository)
	mockSecurityRepository := ProvideSecurityRepositoryMock()
	securityMiddleware := middlewares.ProvideSecurityMiddleware(mockSecurityRepository, mockGasStationRepository, mockSocioSmartService)
	paymentRoutes := routes.ProvidePaymenRoutes(customerAuthMiddleware, paymentController, authMiddleware, securityMiddleware)
	customerController := controllers.ProvideCustomerController(mockStripeService, mockSwitService, configConfig, mockSettingRepository, mockCustomerRepository, mockElegibilityRepository)
	customerRoutes := routes.ProvideCustomerRoutes(customerAuthMiddleware, customerController, authMiddleware)
	mockSynchronizationRepository := ProvideSynchronizationRepository()
	synchronizationController := controllers.ProvideSynchronizationController(mockSynchronizationRepository, mockSynchronizationTask)
	synchronizationRoute := routes.ProvideSynchronizationRoutes(synchronizationController, authMiddleware)
	mockPermissionRepository := ProvidePermissionRepositoryMock()
	permissionController := controllers.ProvidePermissionController(mockPermissionRepository)
	permissionRoutes := routes.ProvidePermissionRoutes(authMiddleware, permissionController)
	settingController := controllers.ProvideSettingController(mockSettingRepository)
	settingRoutes := routes.ProvideSettingRoutes(authMiddleware, settingController)
	campaignController := controllers.ProvideCampaignController(mockCampaignRepository)
	campaignRoutes := routes.ProvideCampaingRoutes(campaignController, authMiddleware)
	elegibilityController := controllers.ProvideElegibityController(mockElegibilityRepository)
	elebilityRoutes := routes.ProvideElebilityRoutes(authMiddleware, elegibilityController)
	routesRoutes := routes.ProvideV1Routes(userRoutes, authRoutes, gasStationRoutes, gasPumpRoutes, paymentRoutes, customerRoutes, synchronizationRoute, permissionRoutes, settingRoutes, campaignRoutes, elebilityRoutes)
	engine := app.ProvideGinApp(configConfig, routesRoutes)
	appWithMock := ProvideAppWithMock(engine, mockUserRepository, mockGasStationRepository, mockGasPumpRepository, mockCustomerRepository, mockPaymentRepository, mockCustomerService, mockStripeService, mockSocioSmartService, mockSynchronizationTask, mockSynchronizationRepository, mockSecurityRepository, mockPermissionRepository, mockSwitService, mockInvoicingService, mockMailService, mockSettingRepository, mockCampaignRepository, mockElegibilityRepository, mockDebitService)
	return appWithMock, nil
}

// wire.go:

// Mocks provider
func ProvideUserRepositoryMock() *repository.MockUserRepository {
	return &repository.MockUserRepository{}
}

func ProvidePermissionRepositoryMock() *repository.MockPermissionRepository {
	return &repository.MockPermissionRepository{}
}

func ProvideGasStationRepositoryMock() *repository.MockGasStationRepository {
	return &repository.MockGasStationRepository{}
}

func ProvideGasPumpRepositoryMock() *repository.MockGasPumpRepository {
	return &repository.MockGasPumpRepository{}
}

func ProvideCustomerRepositoryMock() *repository.MockCustomerRepository {
	return &repository.MockCustomerRepository{}
}

func ProvidePaymentRepositoryMock() *repository.MockPaymentRepository {
	return &repository.MockPaymentRepository{}
}

func ProvideCustomerServiceMock() *services.MockCustomerService {
	return &services.MockCustomerService{}
}

func ProvideStripeServiceMock() *services.MockStripeService {
	return &services.MockStripeService{}
}

func ProvideSocioSmartServiceMock() *services.MockSocioSmartService {
	return &services.MockSocioSmartService{}
}

func ProvideSynchronizationTaskMock() *tasks.MockSynchronizationTask {
	return &tasks.MockSynchronizationTask{}
}

func ProvideSynchronizationRepository() *repository.MockSynchronizationRepository {
	return &repository.MockSynchronizationRepository{}
}

func ProvideSecurityRepositoryMock() *repository.MockSecurityRepository {
	return &repository.MockSecurityRepository{}
}

func ProvideSwitServiceMock() *services.MockSwitService {
	return &services.MockSwitService{}
}

func ProvideInvoicingServiceMock() *services.MockInvoicingService {
	return &services.MockInvoicingService{}
}

func ProvideMailServiceMock() *services.MockMailService {
	return &services.MockMailService{}
}

func ProvideSettingRepositoryMock() *repository.MockSettingRepository {
	return &repository.MockSettingRepository{}
}

func ProvideCampaignRepositoryMock() *repository.MockCampaignRepository {
	return &repository.MockCampaignRepository{}
}

func ProvideElegibilityRepositoryMock() *repository.MockElegibilityRepository {
	return &repository.MockElegibilityRepository{}
}

func ProvideDebitServiceMock() *services.MockDebitService {
	return &services.MockDebitService{}
}

var MockSet = wire.NewSet(
	ProvideUserRepositoryMock,
	ProvideGasStationRepositoryMock,
	ProvideGasPumpRepositoryMock,
	ProvideCustomerRepositoryMock,
	ProvidePaymentRepositoryMock,
	ProvideCustomerServiceMock,
	ProvideStripeServiceMock,
	ProvideSocioSmartServiceMock,
	ProvideSynchronizationTaskMock,
	ProvideSynchronizationRepository,
	ProvideSecurityRepositoryMock,
	ProvidePermissionRepositoryMock,
	ProvideSwitServiceMock,
	ProvideInvoicingServiceMock,
	ProvideMailServiceMock,
	ProvideSettingRepositoryMock,
	ProvideCampaignRepositoryMock,
	ProvideElegibilityRepositoryMock,
	ProvideDebitServiceMock, wire.Bind(new(repository.UserRepository), new(*repository.MockUserRepository)), wire.Bind(new(repository.GasStationRepository), new(*repository.MockGasStationRepository)), wire.Bind(new(repository.GasPumpRepository), new(*repository.MockGasPumpRepository)), wire.Bind(new(repository.CustomerRepository), new(*repository.MockCustomerRepository)), wire.Bind(new(repository.PaymentRepository), new(*repository.MockPaymentRepository)), wire.Bind(new(services.CustomerService), new(*services.MockCustomerService)), wire.Bind(new(services.StripeService), new(*services.MockStripeService)), wire.Bind(new(services.SocioSmartService), new(*services.MockSocioSmartService)), wire.Bind(new(tasks.SynchronizationTask), new(*tasks.MockSynchronizationTask)), wire.Bind(
		new(repository.SynchronizationRepository),
		new(*repository.MockSynchronizationRepository),
	), wire.Bind(new(repository.SecurityRepository), new(*repository.MockSecurityRepository)), wire.Bind(new(repository.PermissionRepository), new(*repository.MockPermissionRepository)), wire.Bind(new(services.SwitService), new(*services.MockSwitService)), wire.Bind(new(services.InvoicingService), new(*services.MockInvoicingService)), wire.Bind(new(services.MailService), new(*services.MockMailService)), wire.Bind(new(repository.SettingRepository), new(*repository.MockSettingRepository)), wire.Bind(new(repository.CampaignRepository), new(*repository.MockCampaignRepository)), wire.Bind(new(repository.ElegibilityRepository), new(*repository.MockElegibilityRepository)), wire.Bind(new(services.DebitService), new(*services.MockDebitService)),
)

type App struct {
	Router *gin.Engine
	DB     *gorm.DB
}

func ProvideApp(router *gin.Engine, db *gorm.DB) *App {
	return &App{
		Router: router,
		DB:     db,
	}
}

type AppWithMock struct {
	Router                        *gin.Engine
	UserRepositoryMock            *repository.MockUserRepository
	GasStationRepositoryMock      *repository.MockGasStationRepository
	GasPumpRepositoryMock         *repository.MockGasPumpRepository
	PaymentRepositoryMock         *repository.MockPaymentRepository
	CustomerRepositoryMock        *repository.MockCustomerRepository
	extCustomerService            *services.MockCustomerService
	stripeServiceMock             *services.MockStripeService
	socioSmartServiceMock         *services.MockSocioSmartService
	synchronizationTaskMock       *tasks.MockSynchronizationTask
	synchronizationRepositoryMock *repository.MockSynchronizationRepository
	securityRepositoryMock        *repository.MockSecurityRepository
	permissionRepositoryMock      *repository.MockPermissionRepository
	switServiceMock               *services.MockSwitService
	invoicingServiceMock          *services.MockInvoicingService
	mailServiceMock               *services.MockMailService
	settingRepositoryMock         *repository.MockSettingRepository
	campaignRepositoryMock        *repository.MockCampaignRepository
	elebilityRepositoryMock       *repository.MockElegibilityRepository
	debitServiceMock              *services.MockDebitService
}

func ProvideAppWithMock(router *gin.Engine,
	userRepository *repository.MockUserRepository,
	gasStationRepository *repository.MockGasStationRepository,
	gasPumpRepository *repository.MockGasPumpRepository,
	customerRepository *repository.MockCustomerRepository,
	paymentRepository *repository.MockPaymentRepository,
	extCustomerService *services.MockCustomerService,
	stripeServiceMock *services.MockStripeService,
	socioSmartServiceMock *services.MockSocioSmartService,
	synchronizationTaskMock *tasks.MockSynchronizationTask,
	synchronizationRepositoryMock *repository.MockSynchronizationRepository,
	securityRepositoryMock *repository.MockSecurityRepository,
	permissionRepositoryMock *repository.MockPermissionRepository,
	switServiceMock *services.MockSwitService,
	invoicingServiceMock *services.MockInvoicingService,
	mailServiceMock *services.MockMailService,
	settingRepositoryMock *repository.MockSettingRepository,
	campaignRepositoryMock *repository.MockCampaignRepository,
	elebilityRepositoryMock *repository.MockElegibilityRepository,
	debitServiceMock *services.MockDebitService,
) *AppWithMock {
	return &AppWithMock{
		Router:                        router,
		UserRepositoryMock:            userRepository,
		GasStationRepositoryMock:      gasStationRepository,
		GasPumpRepositoryMock:         gasPumpRepository,
		PaymentRepositoryMock:         paymentRepository,
		CustomerRepositoryMock:        customerRepository,
		extCustomerService:            extCustomerService,
		stripeServiceMock:             stripeServiceMock,
		socioSmartServiceMock:         socioSmartServiceMock,
		synchronizationTaskMock:       synchronizationTaskMock,
		synchronizationRepositoryMock: synchronizationRepositoryMock,
		securityRepositoryMock:        securityRepositoryMock,
		permissionRepositoryMock:      permissionRepositoryMock,
		switServiceMock:               switServiceMock,
		invoicingServiceMock:          invoicingServiceMock,
		mailServiceMock:               mailServiceMock,
		settingRepositoryMock:         settingRepositoryMock,
		campaignRepositoryMock:        campaignRepositoryMock,
		elebilityRepositoryMock:       elebilityRepositoryMock,
		debitServiceMock:              debitServiceMock,
	}
}
