// Code generated by mockery v2.46.3. DO NOT EDIT.

package tasks

import mock "github.com/stretchr/testify/mock"

// MockSynchronizationTask is an autogenerated mock type for the SynchronizationTask type
type MockSynchronizationTask struct {
	mock.Mock
}

// GenerateElegibilityCustomers provides a mock function with given fields:
func (_m *MockSynchronizationTask) GenerateElegibilityCustomers() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateElegibilityCustomers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SyncGasPumps provides a mock function with given fields:
func (_m *MockSynchronizationTask) SyncGasPumps() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SyncGasPumps")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SyncGasStations provides a mock function with given fields:
func (_m *MockSynchronizationTask) SyncGasStations() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SyncGasStations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockSynchronizationTask creates a new instance of MockSynchronizationTask. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSynchronizationTask(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSynchronizationTask {
	mock := &MockSynchronizationTask{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
