services:
  reverse-proxy:
    # The official v3 Traefik docker image
    restart: unless-stopped
    image: traefik:v3.3
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--log.level=INFO"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - "80:80"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reverse-proxy.rule=Host(`traefik-qa.smartgasnotificaciones.xyz`)"
      - "traefik.http.services.reverse-proxy.loadbalancer.server.port=8080"

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  backend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api-qa.lealtadsmartgas.xyz`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  web:
    build: ./frontend
    stdin_open: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`qa.lealtadsmartgas.xyz`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"
