// Code generated by mockery v2.46.3. DO NOT EDIT.

package repository

import (
	models "smartgas-payment/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockSettingRepository is an autogenerated mock type for the SettingRepository type
type MockSettingRepository struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *MockSettingRepository) GetAll() ([]*models.Setting, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*models.Setting
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Setting, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Setting); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Setting)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: _a0
func (_m *MockSettingRepository) GetByName(_a0 string) (*models.Setting, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *models.Setting
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Setting, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Setting); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Setting)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrCreate provides a mock function with given fields: _a0
func (_m *MockSettingRepository) GetOrCreate(_a0 *models.Setting) (bool, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Setting) (bool, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*models.Setting) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(*models.Setting) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *MockSettingRepository) Update(_a0 string, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockSettingRepository creates a new instance of MockSettingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSettingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSettingRepository {
	mock := &MockSettingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
