// Code generated by mockery v2.46.3. DO NOT EDIT.

package repository

import (
	models "smartgas-payment/internal/models"

	mock "github.com/stretchr/testify/mock"

	schemas "smartgas-payment/internal/schemas"

	uuid "github.com/google/uuid"
)

// MockElegibilityRepository is an autogenerated mock type for the ElegibilityRepository type
type MockElegibilityRepository struct {
	mock.Mock
}

// CreateCustomerLevel provides a mock function with given fields: _a0
func (_m *MockElegibilityRepository) CreateCustomerLevel(_a0 *models.CustomerLevel) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomerLevel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.CustomerLevel) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateLevel provides a mock function with given fields: _a0
func (_m *MockElegibilityRepository) CreateLevel(_a0 *models.Level) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateLevel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Level) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomerLevelList provides a mock function with given fields: _a0, _a1
func (_m *MockElegibilityRepository) CustomerLevelList(_a0 *schemas.Pagination, _a1 any) ([]*models.CustomerLevel, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CustomerLevelList")
	}

	var r0 []*models.CustomerLevel
	var r1 error
	if rf, ok := ret.Get(0).(func(*schemas.Pagination, any) ([]*models.CustomerLevel, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*schemas.Pagination, any) []*models.CustomerLevel); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.CustomerLevel)
		}
	}

	if rf, ok := ret.Get(1).(func(*schemas.Pagination, any) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCustomerLevelByCriterias provides a mock function with given fields: _a0
func (_m *MockElegibilityRepository) GetCustomerLevelByCriterias(_a0 any) (*models.CustomerLevel, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerLevelByCriterias")
	}

	var r0 *models.CustomerLevel
	var r1 error
	if rf, ok := ret.Get(0).(func(any) (*models.CustomerLevel, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(any) *models.CustomerLevel); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CustomerLevel)
		}
	}

	if rf, ok := ret.Get(1).(func(any) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLevelByCriterias provides a mock function with given fields: _a0
func (_m *MockElegibilityRepository) GetLevelByCriterias(_a0 any) (*models.Level, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetLevelByCriterias")
	}

	var r0 *models.Level
	var r1 error
	if rf, ok := ret.Get(0).(func(any) (*models.Level, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(any) *models.Level); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Level)
		}
	}

	if rf, ok := ret.Get(1).(func(any) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LevelList provides a mock function with given fields: _a0, _a1
func (_m *MockElegibilityRepository) LevelList(_a0 *schemas.Pagination, _a1 any) ([]*models.Level, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for LevelList")
	}

	var r0 []*models.Level
	var r1 error
	if rf, ok := ret.Get(0).(func(*schemas.Pagination, any) ([]*models.Level, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*schemas.Pagination, any) []*models.Level); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Level)
		}
	}

	if rf, ok := ret.Get(1).(func(*schemas.Pagination, any) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LevelListAll provides a mock function with given fields:
func (_m *MockElegibilityRepository) LevelListAll() ([]*models.Level, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LevelListAll")
	}

	var r0 []*models.Level
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Level, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Level); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Level)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LevelListAllActive provides a mock function with given fields:
func (_m *MockElegibilityRepository) LevelListAllActive() ([]*models.Level, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LevelListAllActive")
	}

	var r0 []*models.Level
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Level, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Level); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Level)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCustomerLevelByID provides a mock function with given fields: _a0, _a1
func (_m *MockElegibilityRepository) UpdateCustomerLevelByID(_a0 uuid.UUID, _a1 *models.CustomerLevel) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCustomerLevelByID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, *models.CustomerLevel) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, *models.CustomerLevel) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, *models.CustomerLevel) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLevelByID provides a mock function with given fields: _a0, _a1
func (_m *MockElegibilityRepository) UpdateLevelByID(_a0 uuid.UUID, _a1 *models.Level) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLevelByID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, *models.Level) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, *models.Level) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, *models.Level) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockElegibilityRepository creates a new instance of MockElegibilityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockElegibilityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockElegibilityRepository {
	mock := &MockElegibilityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
