// Code generated by mockery v2.46.3. DO NOT EDIT.

package repository

import (
	models "smartgas-payment/internal/models"

	mock "github.com/stretchr/testify/mock"

	schemas "smartgas-payment/internal/schemas"

	uuid "github.com/google/uuid"
)

// MockSynchronizationRepository is an autogenerated mock type for the SynchronizationRepository type
type MockSynchronizationRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *MockSynchronizationRepository) Create(_a0 *models.Synchronization) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Synchronization) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBatchDetails provides a mock function with given fields: _a0
func (_m *MockSynchronizationRepository) CreateBatchDetails(_a0 []*models.SynchronizationDetail) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatchDetails")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*models.SynchronizationDetail) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBatchErrors provides a mock function with given fields: _a0
func (_m *MockSynchronizationRepository) CreateBatchErrors(_a0 []*models.SynchronizationError) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatchErrors")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*models.SynchronizationError) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLastByType provides a mock function with given fields: _a0
func (_m *MockSynchronizationRepository) GetLastByType(_a0 string) (*models.Synchronization, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetLastByType")
	}

	var r0 *models.Synchronization
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Synchronization, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Synchronization); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Synchronization)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: _a0, _a1
func (_m *MockSynchronizationRepository) List(_a0 *schemas.Pagination, _a1 any) ([]*models.Synchronization, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Synchronization
	var r1 error
	if rf, ok := ret.Get(0).(func(*schemas.Pagination, any) ([]*models.Synchronization, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*schemas.Pagination, any) []*models.Synchronization); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Synchronization)
		}
	}

	if rf, ok := ret.Get(1).(func(*schemas.Pagination, any) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDetails provides a mock function with given fields: _a0, _a1
func (_m *MockSynchronizationRepository) ListDetails(_a0 *schemas.Pagination, _a1 any) ([]*models.SynchronizationDetail, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListDetails")
	}

	var r0 []*models.SynchronizationDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(*schemas.Pagination, any) ([]*models.SynchronizationDetail, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*schemas.Pagination, any) []*models.SynchronizationDetail); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.SynchronizationDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(*schemas.Pagination, any) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatusByID provides a mock function with given fields: _a0, _a1
func (_m *MockSynchronizationRepository) UpdateStatusByID(_a0 uuid.UUID, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusByID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockSynchronizationRepository creates a new instance of MockSynchronizationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSynchronizationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSynchronizationRepository {
	mock := &MockSynchronizationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
