// Code generated by mockery v2.46.3. DO NOT EDIT.

package repository

import (
	models "smartgas-payment/internal/models"

	mock "github.com/stretchr/testify/mock"

	schemas "smartgas-payment/internal/schemas"

	uuid "github.com/google/uuid"
)

// MockPaymentRepository is an autogenerated mock type for the PaymentRepository type
type MockPaymentRepository struct {
	mock.Mock
}

// CreateEvent provides a mock function with given fields: _a0
func (_m *MockPaymentRepository) CreateEvent(_a0 *models.PaymentEvent) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.PaymentEvent) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePaymentIntent provides a mock function with given fields: _a0
func (_m *MockPaymentRepository) CreatePaymentIntent(_a0 *models.Payment) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentIntent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Payment) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: _a0
func (_m *MockPaymentRepository) GetByID(_a0 uuid.UUID) (*models.Payment, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Payment, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Payment); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDForCustomer provides a mock function with given fields: _a0, _a1
func (_m *MockPaymentRepository) GetByIDForCustomer(_a0 uuid.UUID, _a1 uuid.UUID) (*models.Payment, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDForCustomer")
	}

	var r0 *models.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (*models.Payment, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) *models.Payment); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDPreloaded provides a mock function with given fields: _a0
func (_m *MockPaymentRepository) GetByIDPreloaded(_a0 uuid.UUID) (*models.Payment, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDPreloaded")
	}

	var r0 *models.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Payment, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Payment); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastEventByPaymentID provides a mock function with given fields: _a0
func (_m *MockPaymentRepository) GetLastEventByPaymentID(_a0 uuid.UUID) (*models.PaymentEvent, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetLastEventByPaymentID")
	}

	var r0 *models.PaymentEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.PaymentEvent, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.PaymentEvent); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PaymentEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentByStripePaymentIntentID provides a mock function with given fields: _a0
func (_m *MockPaymentRepository) GetPaymentByStripePaymentIntentID(_a0 string) (*models.Payment, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentByStripePaymentIntentID")
	}

	var r0 *models.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Payment, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Payment); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStatsForCustomer provides a mock function with given fields: _a0, _a1
func (_m *MockPaymentRepository) GetStatsForCustomer(_a0 uuid.UUID, _a1 StatsForCustomerOpts) (*CustomerStats, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetStatsForCustomer")
	}

	var r0 *CustomerStats
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, StatsForCustomerOpts) (*CustomerStats, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, StatsForCustomerOpts) *CustomerStats); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CustomerStats)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, StatsForCustomerOpts) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: _a0, _a1
func (_m *MockPaymentRepository) List(_a0 *schemas.Pagination, _a1 any) ([]*models.Payment, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(*schemas.Pagination, any) ([]*models.Payment, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*schemas.Pagination, any) []*models.Payment); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(*schemas.Pagination, any) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: _a0, _a1
func (_m *MockPaymentRepository) UpdateByID(_a0 uuid.UUID, _a1 *models.Payment) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, *models.Payment) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, *models.Payment) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, *models.Payment) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockPaymentRepository creates a new instance of MockPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRepository {
	mock := &MockPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
