// Code generated by mockery v2.46.3. DO NOT EDIT.

package repository

import (
	models "smartgas-payment/internal/models"

	mock "github.com/stretchr/testify/mock"

	schemas "smartgas-payment/internal/schemas"

	uuid "github.com/google/uuid"
)

// MockGasStationRepository is an autogenerated mock type for the GasStationRepository type
type MockGasStationRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *MockGasStationRepository) Create(_a0 *models.GasStation) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.GasStation) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByExternalID provides a mock function with given fields: _a0
func (_m *MockGasStationRepository) GetByExternalID(_a0 string) (*models.GasStation, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetByExternalID")
	}

	var r0 *models.GasStation
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.GasStation, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *models.GasStation); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GasStation)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByExternalIDOrCreate provides a mock function with given fields: _a0, _a1
func (_m *MockGasStationRepository) GetByExternalIDOrCreate(_a0 string, _a1 *models.GasStation) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetByExternalIDOrCreate")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *models.GasStation) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, *models.GasStation) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, *models.GasStation) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: _a0
func (_m *MockGasStationRepository) GetByID(_a0 uuid.UUID) (*models.GasStation, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.GasStation
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.GasStation, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.GasStation); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GasStation)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: _a0, _a1
func (_m *MockGasStationRepository) List(_a0 *schemas.Pagination, _a1 any) ([]*models.GasStation, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.GasStation
	var r1 error
	if rf, ok := ret.Get(0).(func(*schemas.Pagination, any) ([]*models.GasStation, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*schemas.Pagination, any) []*models.GasStation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.GasStation)
		}
	}

	if rf, ok := ret.Get(1).(func(*schemas.Pagination, any) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAll provides a mock function with given fields: filters
func (_m *MockGasStationRepository) ListAll(filters any) ([]*models.GasStation, error) {
	ret := _m.Called(filters)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []*models.GasStation
	var r1 error
	if rf, ok := ret.Get(0).(func(any) ([]*models.GasStation, error)); ok {
		return rf(filters)
	}
	if rf, ok := ret.Get(0).(func(any) []*models.GasStation); ok {
		r0 = rf(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.GasStation)
		}
	}

	if rf, ok := ret.Get(1).(func(any) error); ok {
		r1 = rf(filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: _a0, _a1
func (_m *MockGasStationRepository) UpdateByID(_a0 uuid.UUID, _a1 *models.GasStation) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, *models.GasStation) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, *models.GasStation) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, *models.GasStation) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockGasStationRepository creates a new instance of MockGasStationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGasStationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGasStationRepository {
	mock := &MockGasStationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
