// Code generated by mockery v2.46.3. DO NOT EDIT.

package repository

import (
	models "smartgas-payment/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSecurityRepository is an autogenerated mock type for the SecurityRepository type
type MockSecurityRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *MockSecurityRepository) Create(_a0 *models.AuthorizedApplication) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.AuthorizedApplication) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByKeys provides a mock function with given fields: _a0, _a1
func (_m *MockSecurityRepository) GetByKeys(_a0 uuid.UUID, _a1 uuid.UUID) (*models.AuthorizedApplication, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetByKeys")
	}

	var r0 *models.AuthorizedApplication
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (*models.AuthorizedApplication, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) *models.AuthorizedApplication); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AuthorizedApplication)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockSecurityRepository creates a new instance of MockSecurityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecurityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecurityRepository {
	mock := &MockSecurityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
