// Code generated by mockery v2.46.3. DO NOT EDIT.

package repository

import (
	models "smartgas-payment/internal/models"

	mock "github.com/stretchr/testify/mock"

	schemas "smartgas-payment/internal/schemas"

	uuid "github.com/google/uuid"
)

// MockGasPumpRepository is an autogenerated mock type for the GasPumpRepository type
type MockGasPumpRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *MockGasPumpRepository) Create(_a0 *models.GasPump) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.GasPump) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveByID provides a mock function with given fields: _a0
func (_m *MockGasPumpRepository) GetActiveByID(_a0 uuid.UUID) (*models.GasPump, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByID")
	}

	var r0 *models.GasPump
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.GasPump, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.GasPump); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GasPump)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByExternalIDOrCreate provides a mock function with given fields: _a0, _a1
func (_m *MockGasPumpRepository) GetByExternalIDOrCreate(_a0 string, _a1 *models.GasPump) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetByExternalIDOrCreate")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *models.GasPump) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, *models.GasPump) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, *models.GasPump) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByGasStationAndNumber provides a mock function with given fields: _a0, _a1
func (_m *MockGasPumpRepository) GetByGasStationAndNumber(_a0 uuid.UUID, _a1 string) (*models.GasPump, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetByGasStationAndNumber")
	}

	var r0 *models.GasPump
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) (*models.GasPump, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) *models.GasPump); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GasPump)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: _a0
func (_m *MockGasPumpRepository) GetByID(_a0 uuid.UUID) (*models.GasPump, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.GasPump
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.GasPump, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.GasPump); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GasPump)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: _a0, _a1
func (_m *MockGasPumpRepository) List(_a0 *schemas.Pagination, _a1 any) ([]*models.GasPump, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.GasPump
	var r1 error
	if rf, ok := ret.Get(0).(func(*schemas.Pagination, any) ([]*models.GasPump, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*schemas.Pagination, any) []*models.GasPump); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.GasPump)
		}
	}

	if rf, ok := ret.Get(1).(func(*schemas.Pagination, any) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: _a0, _a1
func (_m *MockGasPumpRepository) UpdateByID(_a0 uuid.UUID, _a1 *models.GasPump) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, *models.GasPump) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, *models.GasPump) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, *models.GasPump) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockGasPumpRepository creates a new instance of MockGasPumpRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGasPumpRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGasPumpRepository {
	mock := &MockGasPumpRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
