// Code generated by mockery v2.46.3. DO NOT EDIT.

package repository

import (
	models "smartgas-payment/internal/models"

	mock "github.com/stretchr/testify/mock"

	schemas "smartgas-payment/internal/schemas"

	time "time"

	uuid "github.com/google/uuid"
)

// MockCampaignRepository is an autogenerated mock type for the CampaignRepository type
type MockCampaignRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *MockCampaignRepository) Create(_a0 *models.Campaign) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Campaign) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetApplicableCampaign provides a mock function with given fields: _a0, _a1
func (_m *MockCampaignRepository) GetApplicableCampaign(_a0 time.Time, _a1 uuid.UUID) (*models.Campaign, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetApplicableCampaign")
	}

	var r0 *models.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, uuid.UUID) (*models.Campaign, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(time.Time, uuid.UUID) *models.Campaign); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCampaignByID provides a mock function with given fields: _a0, _a1
func (_m *MockCampaignRepository) GetCampaignByID(_a0 uuid.UUID, _a1 map[string]any) (*models.Campaign, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaignByID")
	}

	var r0 *models.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, map[string]any) (*models.Campaign, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, map[string]any) *models.Campaign); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, map[string]any) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: _a0, _a1
func (_m *MockCampaignRepository) List(_a0 *schemas.Pagination, _a1 any) ([]*models.Campaign, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(*schemas.Pagination, any) ([]*models.Campaign, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(*schemas.Pagination, any) []*models.Campaign); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(*schemas.Pagination, any) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: _a0, _a1
func (_m *MockCampaignRepository) UpdateByID(_a0 uuid.UUID, _a1 *models.Campaign) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, *models.Campaign) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockCampaignRepository creates a new instance of MockCampaignRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCampaignRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCampaignRepository {
	mock := &MockCampaignRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
