// Code generated by mockery v2.46.3. DO NOT EDIT.

package repository

import (
	models "smartgas-payment/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockPermissionRepository is an autogenerated mock type for the PermissionRepository type
type MockPermissionRepository struct {
	mock.Mock
}

// ListAll provides a mock function with given fields:
func (_m *MockPermissionRepository) ListAll() ([]*models.Permission, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []*models.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Permission, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Permission); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAllGroups provides a mock function with given fields:
func (_m *MockPermissionRepository) ListAllGroups() ([]*models.Group, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListAllGroups")
	}

	var r0 []*models.Group
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Group, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Group); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Group)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockPermissionRepository creates a new instance of MockPermissionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPermissionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPermissionRepository {
	mock := &MockPermissionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
