"""First Migration

Revision ID: 1ea25f1c1f9d
Revises: 
Create Date: 2024-10-23 18:56:03.400407

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1ea25f1c1f9d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=20), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id", name="external_id_unique"),
    )
    op.create_table(
        "gas_station_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=10), nullable=False),
        sa.Column("group_name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id", name="external_id_unique"),
    )
    op.create_table(
        "legal_names",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id", name="external_id_unique"),
    )
    op.create_table(
        "deposits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("legal_name_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("amount_used", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["legal_name_id"],
            ["legal_names.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gas_stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("external_id", sa.String(length=10), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("legal_name_id", sa.Integer(), nullable=True),
        sa.Column("cre_permission", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["gas_station_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["legal_name_id"],
            ["legal_names.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id", name="external_id_unique"),
    )
    op.create_table(
        "movements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "DEPOSIT",
                "FUNDS_RESERVED",
                "FUNDS_CONFIRMATION",
                "GIFT_CARD_CREATION",
                "PAYMENT_CANCELED",
                "GIFT_CARD_REDEMPTION",
                name="movementtype",
            ),
            nullable=False,
        ),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("gas_station_id", sa.Integer(), nullable=True),
        sa.Column("deposit_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deposit_id"],
            ["deposits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gas_station_id"],
            ["gas_stations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movements")
    op.drop_table("gas_stations")
    op.drop_table("deposits")
    op.drop_table("legal_names")
    op.drop_table("gas_station_groups")
    op.drop_table("customers")
    # ### end Alembic commands ###
