"""LegalName added to table

Revision ID: 3a41d76c0f47
Revises: c98694289cea
Create Date: 2024-11-02 00:04:06.310931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a41d76c0f47'
down_revision = 'c98694289cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legal_name_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'legal_names', ['legal_name_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('legal_name_id')

    # ### end Alembic commands ###
