"""Added swit transaction id

Revision ID: 3fdf48f0ea6f
Revises: e1dd380f561d
Create Date: 2024-11-12 10:06:34.156738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fdf48f0ea6f'
down_revision = 'e1dd380f561d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
