"""Added gift card table

Revision ID: 6ef2278be9e1
Revises: d4c99076c5fe
Create Date: 2024-10-28 18:52:01.473786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef2278be9e1'
down_revision = 'd4c99076c5fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('amount_used', sa.Float(), nullable=False),
    sa.Column('redeemed', sa.Boolean(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gift_card_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'gift_cards', ['gift_card_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gift_card_id')

    op.drop_table('gift_cards')
    # ### end Alembic commands ###
