"""added card key to gift cards

Revision ID: 71a3d96523bb
Revises: 93451a871456
Create Date: 2024-10-29 17:34:23.684464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a3d96523bb'
down_revision = '93451a871456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_key', sa.String(length=22), nullable=False))
        batch_op.create_unique_constraint('card_key_unique', ['card_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift_cards', schema=None) as batch_op:
        batch_op.drop_constraint('card_key_unique', type_='unique')
        batch_op.drop_column('card_key')

    # ### end Alembic commands ###
