"""Added legal name to gift card

Revision ID: 93451a871456
Revises: 6ef2278be9e1
Create Date: 2024-10-29 04:54:23.808852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93451a871456'
down_revision = '6ef2278be9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legal_name_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'legal_names', ['legal_name_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift_cards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('legal_name_id')

    # ### end Alembic commands ###
