"""Added canceled by field

Revision ID: bb53ee1a9ffd
Revises: e214a618d1d2
Create Date: 2024-11-05 19:59:09.915019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb53ee1a9ffd'
down_revision = 'e214a618d1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canceled_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'authorization', ['canceled_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('canceled_by_id')

    # ### end Alembic commands ###
