"""Payments table

Revision ID: c98694289cea
Revises: 9f868d518685
Create Date: 2024-11-01 21:48:37.845068

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c98694289cea"
down_revision = "9f868d518685"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("gift_card_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("FUNDS_RESERVED", "CONFIRMED", "CANCELLED", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["authorization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gift_card_id"],
            ["gift_cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["authorization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payment_funds_track",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("deposit_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deposit_id"],
            ["deposits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_funds_track")
    op.drop_table("payments")
    # ### end Alembic commands ###
