"""Added geolocation to gas stations

Revision ID: d4c99076c5fe
Revises: 1ea25f1c1f9d
Create Date: 2024-10-28 17:45:02.401917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c99076c5fe'
down_revision = '1ea25f1c1f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gas_stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gas_stations', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
