"""Swit field added

Revision ID: e1dd380f561d
Revises: bb53ee1a9ffd
Create Date: 2024-11-11 22:15:03.828516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1dd380f561d'
down_revision = 'bb53ee1a9ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('swit_customer_id', sa.String(length=100), nullable=False))

    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('DEPOSIT', 'FUNDS_RESERVED', 'FUNDS_CONFIRMATION', 'GIFT_CARD_CREATION', 'GIFT_CARD_REDEMPTION', 'PAYMENT_CANCELED'),
               type_=sa.Enum('DEPOSIT', 'FUNDS_RESERVED', 'FUNDS_CONFIRMATION', 'PAYMENT_CANCELED', 'GIFT_CARD_CREATION', 'GIFT_CARD_REDEMPTION', name='movementtype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('DEPOSIT', 'FUNDS_RESERVED', 'FUNDS_CONFIRMATION', 'PAYMENT_CANCELED', 'GIFT_CARD_CREATION', 'GIFT_CARD_REDEMPTION', name='movementtype'),
               type_=mysql.ENUM('DEPOSIT', 'FUNDS_RESERVED', 'FUNDS_CONFIRMATION', 'GIFT_CARD_CREATION', 'GIFT_CARD_REDEMPTION', 'PAYMENT_CANCELED'),
               existing_nullable=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('swit_customer_id')

    # ### end Alembic commands ###
