"""Payments amounts confirmation and previous

Revision ID: e214a618d1d2
Revises: 9c3ff3c8052e
Create Date: 2024-11-03 14:38:00.693549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e214a618d1d2'
down_revision = '9c3ff3c8052e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_funds_track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prev_amount', sa.Float(), nullable=False))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_confirmed', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('amount_confirmed')

    with op.batch_alter_table('payment_funds_track', schema=None) as batch_op:
        batch_op.drop_column('prev_amount')

    # ### end Alembic commands ###
