"""First migration

Revision ID: 573c02e7ac81
Revises: 
Create Date: 2024-09-19 04:27:07.677208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573c02e7ac81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_name', sa.String(length=255), nullable=False),
    sa.Column('app_key', sa.String(length=40), nullable=False),
    sa.Column('api_key', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('app_key')
    )
    op.create_table('scheduled_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_campaign_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_campaigns')
    op.drop_table('authorization')
    # ### end Alembic commands ###
