"""Scheduled at field added

Revision ID: 931348b77ada
Revises: 573c02e7ac81
Create Date: 2024-09-20 20:20:50.659441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931348b77ada'
down_revision = '573c02e7ac81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_campaigns', schema=None) as batch_op:
        batch_op.drop_column('scheduled_at')

    # ### end Alembic commands ###
